### ISSUE TITLE
Fix `miri` when enable `-Zmiri-tree-borrows`

### ISSUE THREAD

**Issue by al8n** [al8n/skl#34]
See details in #31.

**Comment by JoJoDeveloping** [comment]
I do not quite understand your changes. When I run `cargo test`, I can see that several hundred tests run. But `cargo miri test` only runs one test (excluding doc tests). So where did the other tests go?

**Comment by al8n** [comment]
> I see you changed some things so that it can run under TB 🥳
> 
> However, I do not quite understand your changes. When I run `cargo test`, I can see that several hundred tests run. But `cargo miri test` only runs one test (excluding doc tests). So where did the other tests go?

Hi, because of GitHub's CI does not support thousands of tests run at the same time, so I use `--cfg` to configure them.

To run `miri` for all tests, here is the script.

```shell
MIRIFLAGS="-Zmiri-strict-provenance -Zmiri-disable-isolation -Zmiri-symbolic-alignment-check -Zmiri-tree-borrows" \
RUSTFLAGS="--cfg all_tests" \
cargo miri test --lib
```

**Comment by al8n** [comment]
This one is the CI run without any errors report https://github.com/al8n/skl/actions/runs/10995804286. However, I wrote two more test cases and found that a wired data race was reported on a local variable when CAS failed.

**Comment by al8n** [comment]
Issue #36 is caused by `CompressionPolicy::High`, so feature gate this variant, and without it, this crate is compatible with both SB and TB, details can be found in CI and code coverage [here](https://app.codecov.io/gh/al8n/skl).

Really thanks for pointing out Tree Borrows, learn a lot from fixing it!

**Comment by JoJoDeveloping** [comment]
Thanks again for doing this :)

Note that Tree Borrows is still experimental. The issues here were discovered as part of the experiment. So if you have any pieces of code that you would have expected to work, but had to rewrite to make them work with TB, please tell me.
